"use strict";(self.webpackChunkXUI=self.webpackChunkXUI||[]).push([[56],{8406:function(d,n,e){e.r(n),e.d(n,{demos:function(){return y}});var t=e(15009),r=e.n(t),E=e(99289),c=e.n(E),m=e(67294),v=e(79261),y={"packages-base-src-box-demo-0":{component:m.memo(m.lazy(c()(r()().mark(function f(){var u,o;return r()().wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return l.next=2,Promise.resolve().then(e.bind(e,79261));case 2:return u=l.sent,o=u.Box,l.abrupt("return",{default:function(){return m.createElement(o,{sx:{p:2,bgcolor:"primary.main",color:"common.white"}},"Hello XUI")}});case 5:case"end":return l.stop()}},f)})))),asset:{type:"BLOCK",id:"packages-base-src-box-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Box } from '@xui/base';

export default () => (
  <Box sx={{ p: 2, bgcolor: 'primary.main', color: 'common.white' }}>
    Hello XUI
  </Box>
);`},"@xui/base":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{"@xui/base":v},renderOpts:{compile:function(){var f=c()(r()().mark(function o(){var i,l=arguments;return r()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,e.e(862).then(e.bind(e,16862));case 2:return a.abrupt("return",(i=a.sent).default.apply(i,l));case 3:case"end":return a.stop()}},o)}));function u(){return f.apply(this,arguments)}return u}()}}}},19074:function(d,n,e){e.r(n),e.d(n,{demos:function(){return r}});var t=e(67294),r={}},57293:function(d,n,e){e.r(n),e.d(n,{demos:function(){return f}});var t=e(15009),r=e.n(t),E=e(99289),c=e.n(E),m=e(67294),v=e(9958),y=e(13159),f={"field-demo-0":{component:m.memo(m.lazy(c()(r()().mark(function u(){var o,i,l,I;return r()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,Promise.resolve().then(e.bind(e,9958));case 2:return o=s.sent,i=o.Field,s.next=6,Promise.resolve().then(e.bind(e,13159));case 6:return l=s.sent,I=l.default,s.abrupt("return",{default:function(){return m.createElement(i,{label:"Username"},m.createElement(I,{size:"small",fullWidth:!0}))}});case 9:case"end":return s.stop()}},u)})))),asset:{type:"BLOCK",id:"field-demo-0",refAtomIds:["Field"],dependencies:{"index.jsx":{type:"FILE",value:`import { Field } from '@xui/fields';
import TextField from '@mui/material/TextField';

export default () => (
  <Field label="Username">
    <TextField size="small" fullWidth />
  </Field>
);`},"@xui/fields":{type:"NPM",value:"0.0.1"},undefined:{type:"NPM"}},entry:"index.jsx"},context:{"@xui/fields":v,"@mui/material/TextField":y},renderOpts:{compile:function(){var u=c()(r()().mark(function i(){var l,I=arguments;return r()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,e.e(862).then(e.bind(e,16862));case 2:return s.abrupt("return",(l=s.sent).default.apply(l,I));case 3:case"end":return s.stop()}},i)}));function o(){return u.apply(this,arguments)}return o}()}}}},14369:function(d,n,e){e.r(n),e.d(n,{demos:function(){return r}});var t=e(67294),r={}},3:function(d,n,e){e.r(n),e.d(n,{demos:function(){return y}});var t=e(15009),r=e.n(t),E=e(99289),c=e.n(E),m=e(67294),v=e(55020),y={"input-demo-0":{component:m.memo(m.lazy(c()(r()().mark(function f(){var u,o;return r()().wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return l.next=2,Promise.resolve().then(e.bind(e,55020));case 2:return u=l.sent,o=u.Input,l.abrupt("return",{default:function(){return m.createElement(o,{label:"Email",placeholder:"Enter your email"})}});case 5:case"end":return l.stop()}},f)})))),asset:{type:"BLOCK",id:"input-demo-0",refAtomIds:["Input"],dependencies:{"index.jsx":{type:"FILE",value:`import { Input } from '@xui/input';

export default () => <Input label="Email" placeholder="Enter your email" />;`},"@xui/input":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{"@xui/input":v},renderOpts:{compile:function(){var f=c()(r()().mark(function o(){var i,l=arguments;return r()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,e.e(862).then(e.bind(e,16862));case 2:return a.abrupt("return",(i=a.sent).default.apply(i,l));case 3:case"end":return a.stop()}},o)}));function u(){return f.apply(this,arguments)}return u}()}}}},65095:function(d,n,e){e.r(n),e.d(n,{demos:function(){return r}});var t=e(67294),r={}},7501:function(d,n,e){e.r(n),e.d(n,{demos:function(){return r}});var t=e(67294),r={}},40410:function(d,n,e){e.r(n),e.d(n,{demos:function(){return r}});var t=e(67294),r={}},79261:function(d,n,e){e.r(n),e.d(n,{Box:function(){return t.Z}});var t=e(5616)},9958:function(d,n,e){e.r(n),e.d(n,{Field:function(){return y}});var t=e(67294),r=e(6409),E=e(40476),c=e(5616),m=e(85893),v=function(u){var o=u.label,i=u.children;return(0,m.jsxs)(r.Z,{fullWidth:!0,children:[o?(0,m.jsx)(E.Z,{children:o}):null,(0,m.jsx)(c.Z,{sx:{mt:o?1:0},children:i})]})},y=v},55020:function(d,n,e){e.r(n),e.d(n,{Input:function(){return l}});var t=e(97857),r=e.n(t),E=e(13769),c=e.n(E),m=e(67294),v=e(6409),y=e(40476),f=e(90089),u=e(85893),o=["label"],i=function(a){var s=a.label,p=c()(a,o);return(0,u.jsxs)(v.Z,{fullWidth:!0,children:[s?(0,u.jsx)(y.Z,{children:s}):null,(0,u.jsx)(f.Z,r()({fullWidth:!0},p))]})},l=i},70623:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Base layout component built on MUI Box.",paraId:0,tocIndex:0}]},48182:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Base components for XUI, built on top of MUI.",paraId:0,tocIndex:0}]},44752:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Field wrapper for form controls.",paraId:0,tocIndex:0}]},22921:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Field components for XUI forms.",paraId:0,tocIndex:0}]},69706:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Input component built on MUI Input.",paraId:0,tocIndex:0}]},14688:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Input components for XUI forms.",paraId:0,tocIndex:0}]},67513:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Shared TypeScript types for XUI.",paraId:0,tocIndex:0},{value:`import type { Nullable } from '@xui/types';

const value: Nullable<string> = undefined;
`,paraId:1,tocIndex:0}]},65726:function(d,n,e){e.r(n),e.d(n,{texts:function(){return t}});const t=[{value:"Utility functions for XUI.",paraId:0,tocIndex:0},{value:`import { toArray } from '@xui/utils';

toArray('hello');
toArray(['hello', 'world']);
`,paraId:1,tocIndex:0}]}}]);
